# -*- coding: utf-8 -*-
"""FeederList Proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BW9G5LE3YPWoidM93NavR7sXOF9wNz9A
"""

#phase 1 finalised

import pandas as pd
import openpyxl

def extract_tables_phase1(final_grouped_feeder_xlsx):
    """Phase 1: Read Final Grouped Feeder List and extract unique table IDs based on slot digit length."""
    print("--- Phase 1: Extracting Table / Sheet Numbers from Slots ---")

    df = pd.read_excel(final_grouped_feeder_xlsx)
    table_numbers = []

    for slot in df['slot']:
        slot_str = str(slot).strip()

        if not slot_str or slot_str.lower() == 'nan':
            continue

        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]

        num_digits = len(slot_str)

        if num_digits == 5:
            table_id = slot_str[0]
            table_numbers.append(table_id)
        elif num_digits == 6:
            table_id = slot_str[:2]
            table_numbers.append(table_id)
        else:
            table_id = slot_str[0]
            table_numbers.append(table_id)

    unique_tables = []
    for t in table_numbers:
        if t not in unique_tables:
            unique_tables.append(t)

    print(f"Detected Table/Sheet Numbers (Duplicates Removed): {unique_tables}")
    return unique_tables

def setup_template_sheets_phase2(template_xlsx, unique_tables):
    """Phase 2: Input template file and unique table list to create corresponding sheets in the template workbook."""
    print("\n--- Phase 2: Creating Sheets in Template File ---")

    try:
        wb = openpyxl.load_workbook(template_xlsx)
    except FileNotFoundError:
        print(f"Error: Template file '{template_xlsx}' not found.")
        return None, None

    base_sheet = wb.active

    header_row_idx = None
    for r in range(1, 10):
        row_vals = [base_sheet.cell(row=r, column=c).value for c in range(1, base_sheet.max_column + 1)]
        if any(v and str(v).strip().lower() in ['slot', 'part number', 'part'] for v in row_vals):
            header_row_idx = r
            break

    if not header_row_idx:
        header_row_idx = 4 # Default fallback header row

    print(f"Detected template header row at index: {header_row_idx}")

    created_sheets = {}
    for idx, table_id in enumerate(unique_tables):
        sheet_name = f"Table_{table_id}"
        if idx == 0:
            ws = base_sheet
            ws.title = sheet_name
        else:
            ws = wb.copy_worksheet(base_sheet)
            ws.title = sheet_name

        created_sheets[table_id] = ws
        print(f"-> Created sheet: {sheet_name}")

    return wb, header_row_idx

# Execution
if __name__ == "__main__":
    feeder_list_file = 'Final_Grouped_Feeder_List_STMB.xlsx'
    template_file = 'FeederList_Template.xlsx'

    # Execute Phase 1
    detected_tables = extract_tables_phase1(feeder_list_file)

    # Execute Phase 2
    if detected_tables:
        workbook, header_idx = setup_template_sheets_phase2(template_file, detected_tables)

#phase 2 finalised

import pandas as pd
import openpyxl

def generate_multi_sheet_feeder_list(final_grouped_feeder_xlsx, template_xlsx, output_xlsx_name):
    print("--- Phase 1: Extracting Unique Table/Sheet Numbers from Slots ---")

    try:
        df = pd.read_excel(final_grouped_feeder_xlsx)
    except FileNotFoundError:
        print(f"Error: File '{final_grouped_feeder_xlsx}' not found.")
        return

    table_numbers = []

    for slot in df['slot']:
        slot_str = str(slot).strip()

        if not slot_str or slot_str.lower() == 'nan':
            continue

        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]

        num_digits = len(slot_str)

        if num_digits == 5:
            table_id = slot_str[0]
            table_numbers.append(table_id)
        elif num_digits == 6:
            table_id = slot_str[:2]
            table_numbers.append(table_id)
        else:
            # Fallback for any other digit length
            table_id = slot_str[0]
            table_numbers.append(table_id)

    # Remove duplicate table numbers while preserving the order of appearance
    unique_tables = []
    for t in table_numbers:
        if t not in unique_tables:
            unique_tables.append(t)

    print(f"Detected Table/Sheet Numbers (Duplicates Removed): {unique_tables}")

    print("\n--- Phase 2: Creating Multi-Sheet Template Output File ---")

    # Load the template workbook
    try:
        wb_template = openpyxl.load_workbook(template_xlsx)
    except FileNotFoundError:
        print(f"Error: Template file '{template_xlsx}' not found.")
        return

    base_sheet = wb_template.active

    # Create a sheet for each unique table found in Phase 1
    for idx, table_id in enumerate(unique_tables):
        sheet_name = f"Table_{table_id}"
        if idx == 0:
            ws = base_sheet
            ws.title = sheet_name
        else:
            ws = wb_template.copy_worksheet(base_sheet)
            ws.title = sheet_name
        print(f"-> Created sheet: {sheet_name}")

    # Save as a brand new output file comprising all tables/sheets
    wb_template.save(output_xlsx_name)
    print(f"Successfully generated new output file with {len(unique_tables)} sheets: {output_xlsx_name}")

# Execution
if __name__ == "__main__":
    generate_multi_sheet_feeder_list(
        final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
        template_xlsx='FeederList_Template.xlsx',
        output_xlsx_name='FeederList_Template_extended.xlsx'
    )

#phase 3 finalised

import openpyxl
import pandas as pd

def populate_multisheet_template_phase3(final_grouped_feeder_xlsx, multisheet_template_xlsx, output_final_xlsx):
    print("--- Phase 3: Populating Row 5 with Column Headers ---")

    # 1. Load the final grouped feeder list to extract the column names/fields
    try:
        df_grouped = pd.read_excel(final_grouped_feeder_xlsx)
    except FileNotFoundError:
        print(f"Error: '{final_grouped_feeder_xlsx}' not found.")
        return

    # Extract column header names (slot, subslot, part number, etc.)
    column_headers = df_grouped.columns.tolist()
    print(f"Extracted column headers: {column_headers}")

    # 2. Load the multi-sheet workbook generated from Phase 2
    try:
        wb = openpyxl.load_workbook(multisheet_template_xlsx)
    except FileNotFoundError:
        print(f"Error: Multi-sheet template file '{multisheet_template_xlsx}' not found.")
        return

    # 3. Iterate through every sheet and paste the headers into row 5
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        print(f"-> Writing headers to row 5 on sheet: {sheet_name}")

        # Paste each header name into row 5, starting from column 1 (A)
        for col_idx, header_name in enumerate(column_headers, start=1):
            ws.cell(row=5, column=col_idx, value=header_name)

    # 4. Save the updated multi-sheet workbook
    wb.save(output_final_xlsx)
    print(f"\nPhase 3 Complete! Updated multi-sheet workbook saved as: {output_final_xlsx}")

# Execution Entry Point
if __name__ == "__main__":
    populate_multisheet_template_phase3(
        final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
        multisheet_template_xlsx='FeederList_Template_extended.xlsx',
        output_final_xlsx='FeederList_Template_Headers.xlsx'
    )

#phase 4 testing1
import openpyxl
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

def execute_phase_4_table_copy(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
    fully_populated_multisheet_xlsx='FeederList_Template_Headers.xlsx',
    final_output_xlsx='FeederList_AKS.xlsx'
):
    print("--- Phase 4: Copying Table-Wise Content with Formatting ---")

    # 1. Load source workbook (Final Grouped Feeder List) with openpyxl to preserve styles and merges
    try:
        src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
        src_ws = src_wb.active
    except FileNotFoundError:
        print(f"Error: '{final_grouped_feeder_xlsx}' not found.")
        return

    # 2. Load target multi-sheet workbook from Phase 3
    try:
        target_wb = openpyxl.load_workbook(fully_populated_multisheet_xlsx)
    except FileNotFoundError:
        print(f"Error: '{fully_populated_multisheet_xlsx}' not found.")
        return

    # Map column headers from Row 5 of the target sheets for alignment
    target_header_maps = {}
    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=5, column=c).value
            if val:
                h_map[str(val).strip().lower()] = c
        target_header_maps[sheet_name] = h_map

    # Map source header names from Row 1 (or header row) of src_ws
    src_headers = {}
    for c in range(1, src_ws.max_column + 1):
        val = src_ws.cell(row=1, column=c).value
        if val:
            src_headers[str(val).strip().lower()] = c

    slot_col_idx = src_headers.get('slot', 1)

    # Track insertion row counters for each target sheet
    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}

    # Helper function to determine table ID from slot string
    def get_table_id_from_slot(slot_val):
        slot_str = str(slot_val).strip()
        if not slot_str or slot_str.lower() == 'nan':
            return None
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]
        num_digits = len(slot_str)
        if num_digits == 5:
            return slot_str[0]
        elif num_digits == 6:
            return slot_str[:2]
        else:
            return slot_str[0]

    # Keep track of active slot for sub-rows / alternate parts (forward fill logic)
    current_slot_val = None

    # Iterate through rows starting from row 2 (assuming row 1 is header)
    for r in range(2, src_ws.max_row + 1):
        # Read slot value
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str

        if not current_slot_val:
            continue

        # Determine table ID
        table_id = get_table_id_from_slot(current_slot_val)
        if not table_id:
            continue

        target_sheet_name = f"Table_{table_id}"
        if target_sheet_name not in target_wb.sheetnames:
            continue

        target_ws = target_wb[target_sheet_name]
        target_row = sheet_row_counters[target_sheet_name]
        header_map = target_header_maps[target_sheet_name]

        # Copy each cell from source row to target row, mapping columns correctly and preserving formatting
        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=1, column=src_col_idx).value
            if not src_header_val:
                continue

            col_key = str(src_header_val).strip().lower()
            if col_key in header_map:
                target_col_idx = header_map[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = target_ws.cell(row=target_row, column=target_col_idx)

                # Copy value
                target_cell.value = src_cell.value

                # Copy formatting (font, fill, alignment, border)
                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[target_sheet_name] += 1

    # Save the final populated workbook
    target_wb.save(final_output_xlsx)
    print(f"\nPhase 4 Complete! Final formatted multi-table feeder list saved as: {final_output_xlsx}")

if __name__ == "__main__":
    execute_phase_4_table_copy()

#phase 4 testing2

import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

def generate_dixon_table_wise_feeder_system(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
    template_xlsx='FeederList_Template.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List.xlsx'
):
    print("==================================================")
    print("--- STARTING DIXON TABLE-WISE AUTOMATION PIPELINE ---")
    print("==================================================\n")

    # ==========================================================
    # PHASE 1: Extract Unique Table/Sheet Numbers from Slots
    # ==========================================================
    print("[Phase 1] Extracting table/sheet IDs from slot numbers...")
    try:
        df = pd.read_excel(final_grouped_feeder_xlsx)
    except FileNotFoundError:
        print(f"Error: '{final_grouped_feeder_xlsx}' not found.")
        return

    table_numbers = []
    for slot in df['slot']:
        slot_str = str(slot).strip()
        if not slot_str or slot_str.lower() == 'nan':
            continue
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]

        num_digits = len(slot_str)
        if num_digits == 5:
            table_id = slot_str[0]
            table_numbers.append(table_id)
        elif num_digits == 6:
            table_id = slot_str[:2]
            table_numbers.append(table_id)
        else:
            table_id = slot_str[0]
            table_numbers.append(table_id)

    unique_tables = []
    for t in table_numbers:
        if t not in unique_tables:
            unique_tables.append(t)

    print(f"-> Detected Unique Tables: {unique_tables}\n")

    # ==========================================================
    # PHASE 2: Create Multi-Sheet Workbook with Identical Formatting
    # ==========================================================
    print("[Phase 2] Generating multi-sheet workbook structure & matching sheet formatting...")
    try:
        wb = openpyxl.load_workbook(template_xlsx)
    except FileNotFoundError:
        print(f"Error: Template file '{template_xlsx}' not found.")
        return

    base_sheet = wb.active

    # Capture base sheet column widths and row dimensions to apply to all sheets
    base_col_widths = {col: base_sheet.column_dimensions[col].width for col in base_sheet.column_dimensions}

    created_sheets = {}
    for idx, table_id in enumerate(unique_tables):
        sheet_name = f"Table_{table_id}"
        if idx == 0:
            ws = base_sheet
            ws.title = sheet_name
        else:
            ws = wb.copy_worksheet(base_sheet)
            ws.title = sheet_name

            # Ensure copied sheet matches column widths of base sheet exactly
            for col, width in base_col_widths.items():
                ws.column_dimensions[col].width = width

        created_sheets[table_id] = ws
        print(f"-> Created and formatted sheet: {sheet_name}")
    print()

    # Unmerge cells across all sheets to prevent read-only errors
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for merged_range in list(ws.merged_cells.ranges):
            ws.unmerge_cells(str(merged_range))

    # ==========================================================
    # PHASE 3: Populate Column Headers on Row 5
    # ==========================================================
    print("[Phase 3] Writing column headers onto Row 5 across all sheets...")
    column_headers = df.columns.tolist()

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for col_idx, header_name in enumerate(column_headers, start=1):
            ws.cell(row=5, column=col_idx, value=header_name)
        print(f"-> Headers written to sheet: {sheet_name}")
    print()

    # ==========================================================
    # PHASE 4: Paste Table-Wise Content Starting at Row 6 (Clean Boundaries)
    # ==========================================================
    print("[Phase 4] Grouping and inserting table data starting at Row 6...")
    df['slot_str'] = df['slot'].astype(str).str.strip()
    df['temp_slot'] = df['slot_str'].replace('', pd.NA).ffill()

    def get_table_from_slot(slot_val):
        clean_slot = str(slot_val).split('.')[0].strip()
        if not clean_slot or clean_slot.lower() == 'nan':
            return '1'
        num_digits = len(clean_slot)
        if num_digits == 5:
            return clean_slot[0]
        elif num_digits == 6:
            return clean_slot[:2]
        else:
            return clean_slot[0]

    df['table_id'] = df['temp_slot'].apply(get_table_from_slot)
    tables_dict = dict(tuple(df.groupby('table_id')))

    # Track row counters for each sheet starting at row 6
    sheet_row_counters = {sheet_name: 6 for sheet_name in wb.sheetnames}

    # Load source workbook with styles preserved for copying row data
    src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
    src_ws = src_wb.active

    src_headers = {}
    for c in range(1, src_ws.max_column + 1):
        val = src_ws.cell(row=1, column=c).value
        if val:
            src_headers[str(val).strip().lower()] = c
    slot_col_idx = src_headers.get('slot', 1)

    for r in range(2, src_ws.max_row + 1):
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str
        else:
            # Check if it's a sub-row / alternate part row belonging to current group
            pass

        table_id = get_table_from_slot(slot_cell_val if slot_str else None)
        # Fallback or group assignment
        sheet_name = f"Table_{table_id}"
        if sheet_name not in wb.sheetnames:
            continue

        ws = wb[sheet_name]
        target_row = sheet_row_counters[sheet_name]

        header_mapping = {}
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=5, column=c).value
            if val:
                header_mapping[str(val).strip().lower()] = c

        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=1, column=src_col_idx).value
            if not src_header_val:
                continue
            col_key = str(src_header_val).strip().lower()
            if col_key in header_mapping:
                target_col_idx = header_mapping[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = ws.cell(row=target_row, column=target_col_idx)

                target_cell.value = src_cell.value

                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[sheet_name] += 1

    wb.save(final_output_xlsx)
    print(f"\n==================================================")
    print(f"SUCCESS! Final Output Saved as: {final_output_xlsx}")
    print(f"==================================================")

if __name__ == "__main__":
    generate_dixon_table_wise_feeder_system()

#phase 4 testing 3 (functional)
import openpyxl
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border

def execute_phase_4_table_copy(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
    fully_populated_multisheet_xlsx='FeederList_Template_Headers.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List.xlsx'
):
    print("--- Phase 4: Table-Wise Copy (Preserving Template Top & Alternate Merges) ---")

    # 1. Load source workbook (Final Grouped Feeder List containing grouped alternates) with styles/merges
    try:
        src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
        src_ws = src_wb.active
    except FileNotFoundError:
        print(f"Error: '{final_grouped_feeder_xlsx}' not found.")
        return

    # 2. Load target multi-sheet workbook from Phase 3
    try:
        target_wb = openpyxl.load_workbook(fully_populated_multisheet_xlsx)
    except FileNotFoundError:
        print(f"Error: '{fully_populated_multisheet_xlsx}' not found.")
        return

    # Map column headers from Row 5 of the target sheets
    target_header_maps = {}
    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=5, column=c).value
            if val:
                h_map[str(val).strip().lower()] = c
        target_header_maps[sheet_name] = h_map

    # Map source header names from Row 1 of src_ws
    src_headers = {}
    for c in range(1, src_ws.max_column + 1):
        val = src_ws.cell(row=1, column=c).value
        if val:
            src_headers[str(val).strip().lower()] = c

    slot_col_idx = src_headers.get('slot', 1)

    # Track insertion row counters for each target sheet starting strictly at Row 6
    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}

    # Helper function to determine table ID from slot string (5-digit MSB vs 6-digit left-two digits)
    def get_table_id_from_slot(slot_val):
        slot_str = str(slot_val).strip()
        if not slot_str or slot_str.lower() == 'nan':
            return None
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]
        num_digits = len(slot_str)
        if num_digits == 5:
            return slot_str[0]
        elif num_digits == 6:
            return slot_str[:2]
        else:
            return slot_str[0]

    current_slot_val = None

    # Iterate through source rows starting from row 2 (skipping header)
    for r in range(2, src_ws.max_row + 1):
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str

        if not current_slot_val:
            continue

        table_id = get_table_id_from_slot(current_slot_val)
        if not table_id:
            continue

        target_sheet_name = f"Table_{table_id}"
        if target_sheet_name not in target_wb.sheetnames:
            continue

        target_ws = target_wb[target_sheet_name]
        target_row = sheet_row_counters[target_sheet_name]
        header_map = target_header_maps[target_sheet_name]

        # Copy data cells strictly from Row 6 onwards
        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=1, column=src_col_idx).value
            if not src_header_val:
                continue

            col_key = str(src_header_val).strip().lower()
            if col_key in header_map:
                target_col_idx = header_map[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = target_ws.cell(row=target_row, column=target_col_idx)

                # Copy value
                target_cell.value = src_cell.value

                # Copy styling and formatting
                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[target_sheet_name] += 1

    # Save the final output workbook
    target_wb.save(final_output_xlsx)
    print(f"\nPhase 4 Complete! Saved as: {final_output_xlsx}")

if __name__ == "__main__":
    execute_phase_4_table_copy()

#phase 4 testing 4 (fail)
import openpyxl
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border

def execute_phase_4_table_copy_with_merges(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB_2.xlsx',
    fully_populated_multisheet_xlsx='FeederList_Template_Headers.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List1.xlsx' #write feederlist name here
):
    print("--- Phase 4: Table-Wise Copy with Alternate Part Merging ---")

    # 1. Load source workbook (Final Grouped Feeder List containing grouped alternates)
    try:
        src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
        src_ws = src_wb.active
    except FileNotFoundError:
        # Fallback to standard name if _2 is missing
        try:
            src_wb = openpyxl.load_workbook('Final_Grouped_Feeder_List_STMB.xlsx', data_only=False)
            src_ws = src_wb.active
        except FileNotFoundError:
            print(f"Error: Source grouped feeder list not found.")
            return

    # 2. Load target multi-sheet workbook from Phase 3
    try:
        target_wb = openpyxl.load_workbook(fully_populated_multisheet_xlsx)
    except FileNotFoundError:
        print(f"Error: '{fully_populated_multisheet_xlsx}' not found.")
        return

    # Map column headers from Row 5 of the target sheets
    target_header_maps = {}
    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=5, column=c).value
            if val:
                h_map[str(val).strip().lower()] = c
        target_header_maps[sheet_name] = h_map

    # Map source header names from Row 1 of src_ws
    src_headers = {}
    for c in range(1, src_ws.max_column + 1):
        val = src_ws.cell(row=1, column=c).value
        if val:
            src_headers[str(val).strip().lower()] = c

    slot_col_idx = src_headers.get('slot', 1)
    part_num_col_idx = src_headers.get('part number', 3)
    desc_col_idx = src_headers.get('description', 4)

    # Track insertion row counters for each target sheet starting strictly at Row 6
    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}

    # Track rows inserted per slot per sheet for post-processing alternate merges
    # Format: { sheet_name: { slot_str: [start_row_in_target, end_row_in_target] } }
    slot_row_tracking = {sheet_name: {} for sheet_name in target_wb.sheetnames}

    # Helper function to determine table ID from slot string (5-digit MSB vs 6-digit left-two digits)
    def get_table_id_from_slot(slot_val):
        slot_str = str(slot_val).strip()
        if not slot_str or slot_str.lower() == 'nan':
            return None
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]
        num_digits = len(slot_str)
        if num_digits == 5:
            return slot_str[0]
        elif num_digits == 6:
            return slot_str[:2]
        else:
            return slot_str[0]

    current_slot_val = None

    # Step 1: Copy data rows from source to target sheets starting at Row 6
    for r in range(2, src_ws.max_row + 1):
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str

        if not current_slot_val:
            continue

        table_id = get_table_id_from_slot(current_slot_val)
        if not table_id:
            continue

        target_sheet_name = f"Table_{table_id}"
        if target_sheet_name not in target_wb.sheetnames:
            continue

        target_ws = target_wb[target_sheet_name]
        target_row = sheet_row_counters[target_sheet_name]
        header_map = target_header_maps[target_sheet_name]

        # Track slot rows for merging alternates later
        if current_slot_val not in slot_row_tracking[target_sheet_name]:
            slot_row_tracking[target_sheet_name][current_slot_val] = [target_row, target_row]
        else:
            slot_row_tracking[target_sheet_name][current_slot_val][1] = target_row

        # Copy data cells strictly from Row 6 onwards
        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=1, column=src_col_idx).value
            if not src_header_val:
                continue

            col_key = str(src_header_val).strip().lower()
            if col_key in header_map:
                target_col_idx = header_map[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = target_ws.cell(row=target_row, column=target_col_idx)

                # Copy value
                target_cell.value = src_cell.value

                # Copy styling and formatting
                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[target_sheet_name] += 1

    # Step 2: Apply vertical cell merging for alternate parts (all columns except Part Number & Description)
    for sheet_name, slots_dict in slot_row_tracking.items():
        target_ws = target_wb[sheet_name]
        header_map = target_header_maps[sheet_name]

        # Identify target column indices for part number and description to exclude them from merging
        part_num_col_idx = header_map.get('part number', None)
        desc_col_idx = header_map.get('description', None)

        for slot_key, (start_r, end_r) in slots_dict.items():
            if start_r < end_r:  # Alternate rows found for this slot
                for col_name, col_idx in header_map.items():
                    # Keep part number and description separate across alternate rows
                    if col_idx in [part_num_col_idx, desc_col_idx]:
                        continue

                    try:
                        target_ws.merge_cells(start_row=start_r, start_column=col_idx, end_row=end_r, end_column=col_idx)
                        # Center align merged cells vertically and horizontally for clean presentation
                        for r_idx in range(start_r, end_r + 1):
                            cell = target_ws.cell(row=r_idx, column=col_idx)
                            cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                    except Exception as e:
                        # Handle potential overlapping merge exceptions gracefully
                        pass

    # Save the final output workbook
    target_wb.save(final_output_xlsx)
    print(f"\nPhase 4 Complete with Alternate Merges! Saved as: {final_output_xlsx}")

if __name__ == "__main__":
    execute_phase_4_table_copy_with_merges()

#phase 4 final

import openpyxl
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment, Border

def execute_phase_4_table_copy_with_subslot_merges(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
    fully_populated_multisheet_xlsx='FeederList_Template_Headers.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List2.xlsx' #write feederlist name here <------
):
    print("--- Phase 4: Table-Wise Copy with Subslot-Aware Alternate Merges ---")

    # 1. Load source workbook
    try:
        src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
        src_ws = src_wb.active
    except FileNotFoundError:
        try:
            final_grouped_feeder_xlsx = 'Final_Grouped_Feeder_List_STMB.xlsx'
            src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
            src_ws = src_wb.active
        except FileNotFoundError:
            print(f"Error: Source grouped feeder list not found.")
            return

    # 2. Load target multi-sheet workbook from Phase 3
    try:
        target_wb = openpyxl.load_workbook(fully_populated_multisheet_xlsx)
    except FileNotFoundError:
        print(f"Error: '{fully_populated_multisheet_xlsx}' not found.")
        return

    # Find source header row
    header_row_idx = 1
    src_headers = {}
    for r in range(1, 3):
        temp_headers = {}
        for c in range(1, src_ws.max_column + 1):
            val = src_ws.cell(row=r, column=c).value
            if val:
                temp_headers[str(val).strip().lower()] = c
        if 'slot' in temp_headers:
            header_row_idx = r
            src_headers = temp_headers
            break

    if not src_headers:
        for c in range(1, src_ws.max_column + 1):
            val = src_ws.cell(row=1, column=c).value
            if val:
                src_headers[str(val).strip().lower()] = c

    slot_col_idx = src_headers.get('slot', 1)
    subslot_col_idx = src_headers.get('subslot', 2)

    # Map target sheet headers from Row 5
    target_header_maps = {}
    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=5, column=c).value
            if val:
                h_map[str(val).strip().lower()] = c
        target_header_maps[sheet_name] = h_map

    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}

    # Track rows per unique (slot, subslot) combination per sheet for precise merging
    # Format: { sheet_name: { (slot_str, subslot_str): [start_row, end_row] } }
    subslot_row_tracking = {sheet_name: {} for sheet_name in target_wb.sheetnames}

    def get_table_id_from_slot(slot_val):
        slot_str = str(slot_val).strip()
        if not slot_str or slot_str.lower() == 'nan':
            return None
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]
        num_digits = len(slot_str)
        if num_digits == 5:
            return slot_str[0]
        elif num_digits == 6:
            return slot_str[:2]
        else:
            return slot_str[0]

    current_slot_val = None
    current_subslot_val = ""

    # Step 1: Copy data rows starting right after the source header row
    for r in range(header_row_idx + 1, src_ws.max_row + 1):
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        subslot_cell_val = src_ws.cell(row=r, column=subslot_col_idx).value if subslot_col_idx else ""

        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""
        subslot_str = str(subslot_cell_val).strip() if subslot_cell_val is not None and str(subslot_cell_val).lower() != 'nan' else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str
            current_subslot_val = subslot_str
        elif subslot_str:
            current_subslot_val = subslot_str

        if not current_slot_val:
            continue

        table_id = get_table_id_from_slot(current_slot_val)
        if not table_id:
            continue

        target_sheet_name = f"Table_{table_id}"
        if target_sheet_name not in target_wb.sheetnames:
            continue

        target_ws = target_wb[target_sheet_name]
        target_row = sheet_row_counters[target_sheet_name]
        header_map = target_header_maps[target_sheet_name]

        # Use (slot, subslot) as the unique grouping key to prevent L and R mixing/merging
        tracking_key = (current_slot_val, current_subslot_val)
        if tracking_key not in subslot_row_tracking[target_sheet_name]:
            subslot_row_tracking[target_sheet_name][tracking_key] = [target_row, target_row]
        else:
            subslot_row_tracking[target_sheet_name][tracking_key][1] = target_row

        # Copy data cells strictly from Row 6 onwards
        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=header_row_idx, column=src_col_idx).value
            if not src_header_val:
                continue

            col_key = str(src_header_val).strip().lower()
            if col_key in header_map:
                target_col_idx = header_map[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = target_ws.cell(row=target_row, column=target_col_idx)

                target_cell.value = src_cell.value

                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[target_sheet_name] += 1

    # Step 2: Apply vertical cell merging strictly within each unique (slot, subslot) group
    for sheet_name, tracking_dict in subslot_row_tracking.items():
        target_ws = target_wb[sheet_name]
        header_map = target_header_maps[sheet_name]

        part_num_col_idx = header_map.get('part number', None)
        desc_col_idx = header_map.get('description', None)

        for tracking_key, (start_r, end_r) in tracking_dict.items():
            if start_r < end_r:  # Alternate rows found for this specific subslot
                for col_name, col_idx in header_map.items():
                    if col_idx in [part_num_col_idx, desc_col_idx]:
                        continue  # Keep part number and description unmerged

                    try:
                        target_ws.merge_cells(start_row=start_r, start_column=col_idx, end_row=end_r, end_column=col_idx)
                        for r_idx in range(start_r, end_r + 1):
                            cell = target_ws.cell(row=r_idx, column=col_idx)
                            cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                    except Exception:
                        pass

    target_wb.save(final_output_xlsx)
    print(f"\nPhase 4 Complete with Subslot-Aware Merges! Saved as: {final_output_xlsx}")

if __name__ == "__main__":
    execute_phase_4_table_copy_with_subslot_merges()

import openpyxl
import pandas as pd
from openpyxl.styles import Alignment, Border, Font, PatternFill

def generate_final_dixon_feeder_list(
    final_grouped_feeder_xlsx='Final_Grouped_Feeder_List_STMB.xlsx',
    template_xlsx='FeederList_Template.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List.xlsx'
):
    print("--- Starting All-in-One Dixon Feeder List Automation Pipeline ---")

    # 1. Load source grouped feeder list via pandas and openpyxl
    try:
        df_grouped = pd.read_excel(final_grouped_feeder_xlsx)
    except FileNotFoundError:
        print(f"Error: Grouped feeder list '{final_grouped_feeder_xlsx}' not found.")
        return

    try:
        src_wb = openpyxl.load_workbook(final_grouped_feeder_xlsx, data_only=False)
        src_ws = src_wb.active
    except FileNotFoundError:
        print(f"Error: Source workbook could not be loaded with openpyxl.")
        return

    # 2. Extract Unique Table IDs from Slots (Phase 1 logic)
    table_numbers = []
    for slot in df_grouped['slot']:
        slot_str = str(slot).strip()
        if not slot_str or slot_str.lower() == 'nan':
            continue
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]

        num_digits = len(slot_str)
        if num_digits == 5:
            table_id = slot_str[0]
            table_numbers.append(table_id)
        elif num_digits == 6:
            table_id = slot_str[:2]
            table_numbers.append(table_id)
        else:
            table_id = slot_str[0]
            table_numbers.append(table_id)

    unique_tables = []
    for t in table_numbers:
        if t not in unique_tables:
            unique_tables.append(t)

    print(f"Detected Table/Sheet Numbers: {unique_tables}")
    if not unique_tables:
        print("Error: No valid tables detected from slots.")
        return

    # 3. Load Template & Setup Multi-Sheet Workbook in Memory (Phase 2 logic)
    try:
        target_wb = openpyxl.load_workbook(template_xlsx)
    except FileNotFoundError:
        print(f"Error: Template file '{template_xlsx}' not found.")
        return

    base_sheet = target_wb.active

    for idx, table_id in enumerate(unique_tables):
        sheet_name = f"Table_{table_id}"
        if idx == 0:
            ws = base_sheet
            ws.title = sheet_name
        else:
            ws = target_wb.copy_worksheet(base_sheet)
            ws.title = sheet_name
        print(f"-> Created sheet: {sheet_name}")

    # 4. Populate Row 5 with Column Headers on all sheets (Phase 3 logic)
    column_headers = df_grouped.columns.tolist()
    target_header_maps = {}

    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for col_idx, header_name in enumerate(column_headers, start=1):
            ws.cell(row=5, column=col_idx, value=header_name)
            h_map[str(header_name).strip().lower()] = col_idx
        target_header_maps[sheet_name] = h_map

    # Identify source header row index and layout
    header_row_idx = 1
    src_headers = {}
    for r in range(1, 3):
        temp_headers = {}
        for c in range(1, src_ws.max_column + 1):
            val = src_ws.cell(row=r, column=c).value
            if val:
                temp_headers[str(val).strip().lower()] = c
        if 'slot' in temp_headers:
            header_row_idx = r
            src_headers = temp_headers
            break

    if not src_headers:
        for c in range(1, src_ws.max_column + 1):
            val = src_ws.cell(row=1, column=c).value
            if val:
                src_headers[str(val).strip().lower()] = c

    slot_col_idx = src_headers.get('slot', 1)
    subslot_col_idx = src_headers.get('subslot', 2)

    # 5. Copy Data Rows and Track Subslots for Merges (Phase 4 logic)
    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}
    subslot_row_tracking = {sheet_name: {} for sheet_name in target_wb.sheetnames}

    def get_table_id_from_slot(slot_val):
        slot_str = str(slot_val).strip()
        if not slot_str or slot_str.lower() == 'nan':
            return None
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]
        num_digits = len(slot_str)
        if num_digits == 5:
            return slot_str[0]
        elif num_digits == 6:
            return slot_str[:2]
        else:
            return slot_str[0]

    current_slot_val = None
    current_subslot_val = ""

    for r in range(header_row_idx + 1, src_ws.max_row + 1):
        slot_cell_val = src_ws.cell(row=r, column=slot_col_idx).value
        subslot_cell_val = src_ws.cell(row=r, column=subslot_col_idx).value if subslot_col_idx else ""

        slot_str = str(slot_cell_val).strip() if slot_cell_val is not None else ""
        subslot_str = str(subslot_cell_val).strip() if subslot_cell_val is not None and str(subslot_cell_val).lower() != 'nan' else ""

        if slot_str and slot_str.lower() != 'nan':
            current_slot_val = slot_str
            current_subslot_val = subslot_str
        elif subslot_str:
            current_subslot_val = subslot_str

        if not current_slot_val:
            continue

        table_id = get_table_id_from_slot(current_slot_val)
        if not table_id:
            continue

        target_sheet_name = f"Table_{table_id}"
        if target_sheet_name not in target_wb.sheetnames:
            continue

        target_ws = target_wb[target_sheet_name]
        target_row = sheet_row_counters[target_sheet_name]
        header_map = target_header_maps[target_sheet_name]

        tracking_key = (current_slot_val, current_subslot_val)
        if tracking_key not in subslot_row_tracking[target_sheet_name]:
            subslot_row_tracking[target_sheet_name][tracking_key] = [target_row, target_row]
        else:
            subslot_row_tracking[target_sheet_name][tracking_key][1] = target_row

        # Copy data cells and styles strictly from Row 6 onwards
        for src_col_idx in range(1, src_ws.max_column + 1):
            src_header_val = src_ws.cell(row=header_row_idx, column=src_col_idx).value
            if not src_header_val:
                continue

            col_key = str(src_header_val).strip().lower()
            if col_key in header_map:
                target_col_idx = header_map[col_key]
                src_cell = src_ws.cell(row=r, column=src_col_idx)
                target_cell = target_ws.cell(row=target_row, column=target_col_idx)

                target_cell.value = src_cell.value

                if src_cell.font:
                    target_cell.font = Font(
                        name=src_cell.font.name, size=src_cell.font.size,
                        bold=src_cell.font.bold, italic=src_cell.font.italic,
                        color=src_cell.font.color
                    )
                if src_cell.fill and src_cell.fill.fill_type:
                    target_cell.fill = PatternFill(
                        fill_type=src_cell.fill.fill_type,
                        start_color=src_cell.fill.start_color,
                        end_color=src_cell.fill.end_color
                    )
                if src_cell.alignment:
                    target_cell.alignment = Alignment(
                        horizontal=src_cell.alignment.horizontal,
                        vertical=src_cell.alignment.vertical,
                        wrap_text=src_cell.alignment.wrap_text
                    )
                if src_cell.border:
                    target_cell.border = Border(
                        left=src_cell.border.left, right=src_cell.border.right,
                        top=src_cell.border.top, bottom=src_cell.border.bottom
                    )

        sheet_row_counters[target_sheet_name] += 1

    # 6. Apply vertical cell merging strictly within each unique (slot, subslot) group
    for sheet_name, tracking_dict in subslot_row_tracking.items():
        target_ws = target_wb[sheet_name]
        header_map = target_header_maps[sheet_name]

        part_num_col_idx = header_map.get('part number', None)
        desc_col_idx = header_map.get('description', None)

        for tracking_key, (start_r, end_r) in tracking_dict.items():
            if start_r < end_r:
                for col_name, col_idx in header_map.items():
                    if col_idx in [part_num_col_idx, desc_col_idx]:
                        continue  # Keep part number and description unmerged

                    try:
                        target_ws.merge_cells(start_row=start_r, start_column=col_idx, end_row=end_r, end_column=col_idx)
                        for r_idx in range(start_r, end_r + 1):
                            cell = target_ws.cell(row=r_idx, column=col_idx)
                            cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                    except Exception:
                        pass

    # Save final output directly
    target_wb.save(final_output_xlsx)
    print(f"\nPipeline Complete! Final Dixon Feeder List saved directly as: {final_output_xlsx}")

if __name__ == "__main__":
    generate_final_dixon_feeder_list(
        final_grouped_feeder_xlsx='Final_Grouped_Feeder_List.xlsx',
        template_xlsx='FeederList_Template.xlsx',
        final_output_xlsx='Final_Complete_Dixon_Feeder_List.xlsx'
    )

import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border

def generate_complete_dixon_feeder_list(
    feeder_csv='STOCKHOLM_5G_FEEDER_SETUP.csv',
    bom_file='SB28F39654 LDA NEW BOM.XLSX',
    template_xlsx='FeederList_Template.xlsx',
    final_output_xlsx='Final_Complete_Dixon_Feeder_List.xlsx'
):
    print("==================================================")
    print("--- STARTING ALL-IN-ONE DIXON FEEDER PIPELINE ---")
    print("==================================================\n")

    # ----------------------------------------------------------
    # STEP 1: Process & Clean Feeder Setup
    # ----------------------------------------------------------
    print("[Step 1] Processing & Cleaning Feeder Setup...")
    try:
        df_feeder = pd.read_csv(feeder_csv, skiprows=6)
    except FileNotFoundError:
        print(f"Error: Feeder CSV file not found at '{feeder_csv}'.")
        return
    except Exception as e:
        print(f"Error loading Feeder CSV file '{feeder_csv}': {e}")
        return

    df_feeder.columns = df_feeder.columns.str.strip()

    column_mapping = {
        'Slot': 'slot',
        'SubSlot': 'subslot',
        'Part': 'part number',
        'Part Description': 'description',
        'Supply': 'supply',
        'Placements': 'placement',
        'BOT': 'BOT Placement',
        'TOP': 'TOP Placement',
        'BOT Designators': 'BOT Designators',
        'TOP Designators': 'TOP Designators'
    }

    existing_columns = {col: column_mapping[col] for col in df_feeder.columns if col in column_mapping}
    df_feeder = df_feeder.rename(columns=existing_columns)

    desired_column_order = [
        'slot', 'subslot', 'part number', 'description', 'supply',
        'placement', 'BOT Placement', 'TOP Placement', 'BOT Designators', 'TOP Designators'
    ]

    final_feeder_cols = [col for col in desired_column_order if col in df_feeder.columns]
    if not final_feeder_cols:
        print("Error: No target columns found in feeder setup after renaming.")
        return

    df_feeder = df_feeder[final_feeder_cols].copy()

    # ----------------------------------------------------------
    # STEP 2: Process & Clean BOM File
    # ----------------------------------------------------------
    print("[Step 2] Processing & Cleaning BOM...")
    try:
        bom_lower = bom_file.lower()
        if bom_lower.endswith('.csv'):
            df_bom = pd.read_csv(bom_file, engine='python')
        elif bom_lower.endswith(('.xlsx', '.xls')):
            df_bom = pd.read_excel(bom_file)
        else:
            print(f"Error: Unsupported file format for {bom_file}.")
            return
    except FileNotFoundError:
        print(f"Error: BOM file not found at '{bom_file}'.")
        return
    except Exception as e:
        print(f"Error loading BOM file '{bom_file}': {e}")
        return

    df_bom.columns = df_bom.columns.str.strip()
    target_cols = ['Component/Item Code', 'Item Description', 'Group']

    missing_cols = [col for col in target_cols if col not in df_bom.columns]
    if missing_cols:
        print(f"!!! ERROR: Missing required columns in BOM file: {missing_cols}")
        return

    df_bom = df_bom[target_cols].copy()

    # ----------------------------------------------------------
    # STEP 3: Group Expansion & Cell Blanking (In Memory)
    # ----------------------------------------------------------
    print("[Step 3] Performing Group Expansion & Cell Blanking...")
    df_feeder['part number'] = df_feeder['part number'].astype(str).str.strip()
    df_bom['Component/Item Code'] = df_bom['Component/Item Code'].astype(str).str.strip()

    group_map = df_bom.groupby('Group').apply(
        lambda x: x[['Component/Item Code', 'Item Description']].to_dict('records')
    ).to_dict()

    part_to_group = dict(zip(df_bom['Component/Item Code'], df_bom['Group']))
    part_to_description = dict(zip(df_bom['Component/Item Code'], df_bom['Item Description']))

    expanded_rows = []

    for _, row in df_feeder.iterrows():
        part_num = row['part number']
        group = part_to_group.get(part_num)

        if pd.notna(group) and group in group_map:
            members = group_map[group]
            for i, member in enumerate(members):
                new_row = row.copy()
                new_row['part number'] = member['Component/Item Code']
                new_row['description'] = member['Item Description']

                if i > 0:
                    leader_cols = [
                        'slot', 'subslot', 'supply', 'placement',
                        'BOT Placement', 'TOP Placement', 'BOT Designators', 'TOP Designators'
                    ]
                    for col in leader_cols:
                        if col in new_row:
                            new_row[col] = ''
                expanded_rows.append(new_row)
        else:
            new_row = row.copy()
            if part_num in part_to_description:
                new_row['description'] = part_to_description[part_num]
            expanded_rows.append(new_row)

    df_expanded = pd.DataFrame(expanded_rows)

    # ----------------------------------------------------------
    # STEP 4: Table Extraction & Multi-Sheet Setup
    # ----------------------------------------------------------
    print("[Step 4] Extracting Table IDs and Setting Up Multi-Sheet Workbook...")
    table_numbers = []
    for slot in df_expanded['slot']:
        slot_str = str(slot).strip()
        if not slot_str or slot_str.lower() == 'nan':
            continue
        if '.' in slot_str:
            slot_str = slot_str.split('.')[0]

        num_digits = len(slot_str)
        if num_digits == 5:
            table_id = slot_str[0]
            table_numbers.append(table_id)
        elif num_digits == 6:
            table_id = slot_str[:2]
            table_numbers.append(table_id)
        else:
            table_id = slot_str[0]
            table_numbers.append(table_id)

    unique_tables = []
    for t in table_numbers:
        if t not in unique_tables:
            unique_tables.append(t)

    print(f"-> Detected Unique Tables: {unique_tables}")
    if not unique_tables:
        print("Error: No valid tables detected from slots.")
        return

    try:
        target_wb = openpyxl.load_workbook(template_xlsx)
    except FileNotFoundError:
        print(f"Error: Template file '{template_xlsx}' not found.")
        return

    base_sheet = target_wb.active
    for idx, table_id in enumerate(unique_tables):
        sheet_name = f"Table_{table_id}"
        if idx == 0:
            ws = base_sheet
            ws.title = sheet_name
        else:
            ws = target_wb.copy_worksheet(base_sheet)
            ws.title = sheet_name
        print(f"-> Created sheet: {sheet_name}")

    # ----------------------------------------------------------
    # STEP 5: Populate Headers and Data Table-Wise
    # ----------------------------------------------------------
    print("[Step 5] Populating Headers & Inserting Data Table-Wise...")
    column_headers = df_expanded.columns.tolist()
    target_header_maps = {}

    for sheet_name in target_wb.sheetnames:
        ws = target_wb[sheet_name]
        h_map = {}
        for col_idx, header_name in enumerate(column_headers, start=1):
            ws.cell(row=5, column=col_idx, value=header_name)
            h_map[str(header_name).strip().lower()] = col_idx
        target_header_maps[sheet_name] = h_map

    df_expanded['slot_str'] = df_expanded['slot'].astype(str).str.strip()
    df_expanded['temp_slot'] = df_expanded['slot_str'].replace('', pd.NA).ffill()

    def get_table_from_slot(slot_val):
        clean_slot = str(slot_val).split('.')[0].strip()
        if not clean_slot or clean_slot.lower() == 'nan':
            return '1'
        num_digits = len(clean_slot)
        if num_digits == 5:
            return clean_slot[0]
        elif num_digits == 6:
            return clean_slot[:2]
        else:
            return clean_slot[0]

    df_expanded['table_id'] = df_expanded['temp_slot'].apply(get_table_from_slot)
    tables_dict = dict(tuple(df_expanded.groupby('table_id')))

    subslot_row_tracking = {sheet_name: {} for sheet_name in target_wb.sheetnames}
    sheet_row_counters = {sheet_name: 6 for sheet_name in target_wb.sheetnames}

    current_active_slot = None
    current_active_subslot = ""

    for table_id, group_df in tables_dict.items():
        sheet_name = f"Table_{table_id}"
        if sheet_name not in target_wb.sheetnames:
            continue

        ws = target_wb[sheet_name]
        header_map = target_header_maps[sheet_name]

        for _, row in group_df.iterrows():
            target_row = sheet_row_counters[sheet_name]

            slot_val = row.get('slot', '')
            subslot_val = row.get('subslot', '')

            slot_str = str(slot_val).strip() if slot_val is not None else ""
            subslot_str = str(subslot_val).strip() if subslot_val is not None and str(subslot_val).lower() != 'nan' else ""

            if slot_str and slot_str.lower() != 'nan':
                current_active_slot = slot_str
                current_active_subslot = subslot_str
            elif subslot_str:
                current_active_subslot = subslot_str

            tracking_key = (current_active_slot, current_active_subslot)
            if tracking_key not in subslot_row_tracking[sheet_name]:
                subslot_row_tracking[sheet_name][tracking_key] = [target_row, target_row]
            else:
                subslot_row_tracking[sheet_name][tracking_key][1] = target_row

            for col_name, val in row.items():
                if col_name in ['slot_str', 'temp_slot', 'table_id']:
                    continue
                col_lower = str(col_name).strip().lower()
                if col_lower in header_map:
                    target_col_idx = header_map[col_lower]
                    cell_val = val if pd.notna(val) else ""
                    ws.cell(row=target_row, column=target_col_idx, value=cell_val)

            sheet_row_counters[sheet_name] += 1

    # ----------------------------------------------------------
    # STEP 6: Apply Subslot-Aware Cell Merging
    # ----------------------------------------------------------
    print("[Step 6] Applying Subslot-Aware Vertical Cell Merging...")
    for sheet_name, tracking_dict in subslot_row_tracking.items():
        ws = target_wb[sheet_name]
        header_map = target_header_maps[sheet_name]

        part_num_col_idx = header_map.get('part number', None)
        desc_col_idx = header_map.get('description', None)

        for tracking_key, (start_r, end_r) in tracking_dict.items():
            if start_r < end_r:
                for col_name, col_idx in header_map.items():
                    if col_idx in [part_num_col_idx, desc_col_idx]:
                        continue
                    try:
                        ws.merge_cells(start_row=start_r, start_column=col_idx, end_row=end_r, end_column=col_idx)
                        for r_idx in range(start_r, end_r + 1):
                            cell = ws.cell(row=r_idx, column=col_idx)
                            cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
                    except Exception:
                        pass

    target_wb.save(final_output_xlsx)
    print(f"\n==================================================")
    print(f"SUCCESS! Final Feeder List saved as: {final_output_xlsx}")
    print(f"==================================================")

if __name__ == "__main__":
    generate_complete_dixon_feeder_list(
        feeder_csv='STOCKHOLM_5G_FEEDER_SETUP.csv',
        bom_file='SB28F39654 LDA NEW BOM.XLSX',
        template_xlsx='FeederList_Template.xlsx',
        final_output_xlsx='Stockholm_5G_8+128_V1_A00_8+1.xlsx'
    )